<?php return array (
    'manage.*' => 'Пълни права в платформата',
    'administration.*' => 'Всички права',
//    'administration.rzs.*' => 'Всички права',
    'administration.rzs_sections' => 'Регистър ЗС (Раздели)',
    'administration.rzs_items' => 'Регистър ЗС (Задължените субекти)',
    'administration.system_classification' => 'Системни класификации',
    'administration.activity_log' => 'Обща активност',
    'users.*' => 'Всички права',
    'roles_permissions.*' => 'Всички права',
    'pdoi.*' => 'Всички права',
    'pdoi.web' => 'ПДОИ - Външно приложение',
    'application.*' => 'Всички права',
    'application.view' => 'Достъп до Заявления (търсене и преглед)',
    'application.edit' => 'Обработка на заявления',
);
